date_patterns = [
    {"label": "DATE", "pattern": [{"LOWER": {"REGEX" : "^\d{1,2}$"}}, {"LOWER": {"REGEX": "^(jan(vier)?)|(f[e|é]v(rier)?)|(mars?)|(avr(il)?)|(mai)|(juin)|(jui(llet)?)|(ao[u|û]t)|(sep(tembre)?)|(oct(obre)?)|(nov(embre)?)|(d[é|e]c(embre)?)$"}}]},
    {"label": "DATE", "pattern": [{"LOWER": {"REGEX" : "^\d{1,2}$"}}, {"LOWER": {"REGEX": "^(jan(vier)?)|(f[e|é]v(rier)?)|(mars?)|(avr(il)?)|(mai)|(juin)|(jui(llet)?)|(ao[u|û]t)|(sep(tembre)?)|(oct(obre)?)|(nov(embre)?)|(d[é|e]c(embre)?)$"}}, {"LOWER": {"REGEX" : "^\d{4}$"}}]},
    {"label": "DATE", "pattern": [{"LOWER": {"REGEX" : "^[0-3]\d\/[0-1][0-9]\/\d{2,4}$"}}]},
    {"label": "DATE", "pattern": [{"LOWER": {"REGEX" : "^[0-3]\d-[0-1][0-9]-\d{2,4}$"}}]},
    {"label": "DATE", "pattern": [{"LOWER": {"REGEX" : "^[0-3]\d\/[0-1][0-9]$"}}]}

]

date_range_patterns = [
    {"label": "DATE_RANGE", "pattern": [{"LOWER": {"REGEX" : "^\d{1,2}$"}}, {"LOWER": {"REGEX": "^(jan(vier)?)|(f[e|é]v(rier)?)|(mars?)|(avr(il)?)|(mai)|(juin)|(jui(llet)?)|(ao[u|û]t)|(sep(tembre)?)|(oct(obre)?)|(nov(embre)?)|(d[é|e]c(embre)?)$"}}, {"LOWER": "au"}, {"LOWER": {"REGEX" : "^\d{1,2}$"}}, {"LOWER": {"REGEX": "^(jan(vier)?)|(f[e|é]v(rier)?)|(mars?)|(avr(il)?)|(mai)|(juin)|(jui(llet)?)|(ao[u|û]t)|(sep(tembre)?)|(oct(obre)?)|(nov(embre)?)|(d[é|e]c(embre)?)$"}}]},
    {"label": "DATE_RANGE", "pattern": [{"LOWER": {"REGEX" : "^\d{1,2}$"}}, {"LOWER": "au"}, {"LOWER": {"REGEX" : "^\d{1,2}$"}}, {"LOWER": {"REGEX": "^(jan(vier)?)|(f[e|é]v(rier)?)|(mars?)|(avr(il)?)|(mai)|(juin)|(jui(llet)?)|(ao[u|û]t)|(sep(tembre)?)|(oct(obre)?)|(nov(embre)?)|(d[é|e]c(embre)?)$"}}]},
    {"label": "DATE_RANGE", "pattern": [{"LOWER": {"REGEX" : "^depuis$"}}, {"LOWER": {"REGEX" : "^hier$"}}]},
    {"label": "DATE_RANGE", "pattern": [{"LOWER": {"REGEX" : "^depuis$"}}, {"LOWER": {"REGEX" : "^\d+$"}}, {"LOWER": {"REGEX" : "^(jours?)|(mois)|(ans?)|(semaines?)$"}}]}
]

comp_patterns = [
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^filtres?$"}}, {"LOWER": {"REGEX" : "^thermiques?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^cuves?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^circuits?$"}}, {"LOWER": {"REGEX" : "^primaires?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^r[é|e]acteurs?$"}}, {"LOWER": {"REGEX" : "^nucl[é|e]aires?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^pompes?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^pompes?$"}}, {"LOWER": "de"}, {"LOWER": {"REGEX" : "^secours$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^vannes?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^cam[é|e]ras?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^cam[é|e]ras?$"}}, {"LOWER": {"REGEX" : "^th[é|e]rmiques?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^relais?$"}}, {"LOWER": {"REGEX" : "^statiques?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^relais?$"}}, {"LOWER": {"REGEX" : "^[é|e]lectrom[é|e]caniques?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^syst[e|è]mes?$"}}, {"LOWER": "de"}, {"LOWER": {"REGEX" : "^ventilations?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^clapets?$"}}, {"LOWER": {"REGEX" : "^anti-retours?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^groupes?$"}}, {"LOWER": {"REGEX" : "^[é|e]lectrog[e|è]nes?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^serveurs?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^thermocouples?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^turbines?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^ventilateurs?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^d[é|e]tecteurs?$"}}, {"LOWER": "de"}, {"LOWER": {"REGEX" : "^mouvements?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^d[é|e]tecteurs?$"}}, {"LOWER": "de"}, {"LOWER": {"REGEX" : "^rayonnements?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^g[é|e]n[é|e]rateurs?$"}}, {"LOWER": "de"}, {"LOWER": {"REGEX" : "^vapeurs?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^circuits?$"}}, {"LOWER": "^secondaires?$"}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^circuits?$"}}, {"LOWER": "de"}, {"LOWER": {"REGEX" : "^refroidissements?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^circuits?$"}}, {"LOWER": "^tertiaires?$"}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^pressuriseurs?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^caloporteurs?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^modérateurs?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^enceintes?$"}}, {"LOWER": "de"}, {"LOWER": {"REGEX" : "^confinements?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^[é|e]changeurs?$"}}, {"LOWER": "^thermiques?$"}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^pompes?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^roues?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^gmpps?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^gaines?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^combustibles?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^reservoirs?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^pistons?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^soupapes?$"}}]},
    {"label": "COMPOSANT", "pattern": [{"LOWER": {"REGEX" : "^cryopompes?$"}}]}
]

doc_patterns = [
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^manuels?$"}}]},
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^manuels?$"}},{"LOWER": "d"}, {"LOWER": {"REGEX" : "^utilisations?$"}}]},
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^manuels?$"}},{"LOWER": {"REGEX" : "^d'utilisations?$"}}]},
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^notices?$"}}]},
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^dossiers?$"}}]},
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^diagrammes?$"}}]},
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^courbes?$"}}, {"LOWER": "de"}, {"LOWER": {"REGEX" : "^d[e|é]faillances?$"}}]},
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^historiques?$"}}]},
    {"label": "DOCUMENT", "pattern": [{"LOWER": {"REGEX" : "^r[è|e|é]glements?$"}}]}
]

serial_numbers_pattern = [
    {"label": "SERIAL_NUMBER", "pattern": [{"LOWER": {"REGEX" : "\d{5,}"}}]},
    {"label": "SERIAL_NUMBER", "pattern": [{"LOWER": {"REGEX" : "^[a-z]+\d{2,}$"}}]}
]

informations_pattern = [
    {"label": "INFO_TYPE_VALUE", "pattern": [{"LOWER": {"REGEX" : "^pression$"}}]},
    {"label": "INFO_TYPE_VALUE", "pattern": [{"LOWER": {"REGEX" : "^dur[é|e]e$"}}, {"LOWER": "de"}, {"LOWER": "vie"}]}
]

event_pattern = [
    {"label": "EVENT", "pattern": [{"LOWER": {"REGEX" : "^maintenances?$"}}]},
    {"label": "EVENT", "pattern": [{"LOWER": {"REGEX" : "^installations?$"}}]},
    {"label": "EVENT", "pattern": [{"LOWER": {"REGEX" : "^r[é|e]parations?$"}}]},
    {"label": "EVENT", "pattern": [{"LOWER": {"REGEX" : "^pannes?$"}}]},
    {"label": "EVENT", "pattern": [{"LOWER": {"REGEX" : "^test$"}}]}
]

sigle_pattern_nuc = [
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^aad$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^abp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^adg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ahp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^apa$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^apg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^are$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^asg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^atd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cet$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cex$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cfi$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cpa$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^crf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cta$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cte$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ctf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cvf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cvi$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^cvp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^da *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dab$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dad$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^daf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dak$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dal$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dam$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dan$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dap$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^daq$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dar$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^daw$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dc *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dcb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dcl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dd .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dda$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^de *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^deb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^del$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^deq$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^der$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^df *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dfb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dfl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dm *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmh$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmk$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dml$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmm$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmn$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmq$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dms$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dmw$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dn *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dng$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnk$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnm$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnn$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnq$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dns$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnw$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dnx$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dny$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dps$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ds *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsi$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsk$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsm$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsn$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsq$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dss$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsw$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dsy$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dt .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dte$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dtf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dtl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dtv$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dv *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dve$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvj$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvm$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvn$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvo$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvt$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvw$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dvy$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dw *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dwa$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dwb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dwk$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dwl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dwn$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dwq$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dwu$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dww$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^dx *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^eau$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^eba$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ede$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^enc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^epp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ety$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^evf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^evr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^evu$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^fa .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^fal$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^far$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^fan$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^fmn$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^fmr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gca$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gct$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gea$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gev$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gex$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gfr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ggr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ghe$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gme$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gpa$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gpv$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gre$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^grh$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^grv$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gse$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gss$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gst$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gsy$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gth$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^gtr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ja .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jac$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jan$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jd .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jdt$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jg *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jgf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jp *$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jpb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jpd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jph$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jpi$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jpo$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jps$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jpt$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^jpv$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ka .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kac$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kae$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kc .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kcc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kch$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kcl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kcm$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kco$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kcp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kcq$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kcu$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kdc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kdo$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kdm$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ker$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kg .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kge$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ki .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kic$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kil$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kie$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kir$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kk .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kkd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kkk$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kko$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kkv$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kkx$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kl .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kle$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kli$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kme$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kos$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kpe$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kr .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kra$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^krc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^krg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^krh$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^krs$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^krt$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ks .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ksc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ksd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ksq$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ksu$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kt .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ktg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kz .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kzc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^kzr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^la .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lg .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lh .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^li .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lj .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lk .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ll .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lo.$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ls .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lsa$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lsi$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ltr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lv .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ly .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^lys$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^pma$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^pmc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^pmg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^pmo$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ptr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rbs$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rcp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rcv$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rea$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ren$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^res$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rgl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ric$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ris$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rpe$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rpn$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rpr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rri$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^rsc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sa .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^saa$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sap$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sar$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sat$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sb .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sbe$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sd .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sda$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sdb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sdd$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sdr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sds$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^se .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sea$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^seb$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sec$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sed$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sef$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^seh$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sei$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sek$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sel$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sen$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^seo$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sep$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ser$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^seu$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sez$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sf .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sfi$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sg .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sga$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sgc$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sgh$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sgl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sgn$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sgo$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sgz$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^si .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sir$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sit$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sk .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^skl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^skr$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^skz$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sn .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^snl$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sr .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sri$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sru$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ssf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^st .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ste$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^stf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sv .$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^sva$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^teg$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^tek$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ten$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^tep$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ter$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^tes$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^teu$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^tri$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^tsf$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^vda$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^vpu$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^vvp$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ybm$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ygv$"""}}]},
{"label": "SIGLE", "pattern": [{"LOWER": {"REGEX" : """^ylv$"""}}]},
]